language: node_js
node_js:
  - '6'
  - node
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
before_script:
  - npm install
after_success:
  - npm i coveralls
  - "./node_modules/coveralls/bin/coveralls.js < ./backend/coverage/lcov.info"
before_install:
  - openssl aes-256-cbc -K $encrypted_8fee40646b40_key -iv $encrypted_8fee40646b40_iv -in client-secret.json.enc -out client-secret.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
       curl https://sdk.cloud.google.com | bash;
    fi
  - gcloud auth activate-service-account --key-file client-secret.json
install:
  - gcloud config set project first-discovery-166919
  - gcloud config set compute/zone europe-west1
  - gcloud compute instances list
